Counter		EQU	59H	;¼ÆÊýÆ÷£¬ÏÔÊ¾³ÌÐòÍ¨¹ýËüµÃÖªÏÖÕýÏÔÊ¾ÄÄ¸öÊýÂë¹Ü
FIRST		EQU	P2.7	;µÚÒ»Î»ÊýÂë¹ÜµÄÎ»¿ØÖÆ
SECOND  	EQU	P2.6	;µÚ¶þÎ»ÊýÂë¹ÜµÄÎ»¿ØÖÆ
DISPBUFF	EQU	5AH	;ÏÔÊ¾»º³åÇøÎª5AHºÍ5BH
	ORG	0000H
	AJMP	START
	ORG	000BH		;¶¨Ê±Æ÷T0µÄÈë¿Ú
	AJMP	DISP		;ÏÔÊ¾³ÌÐò
	ORG	30H
START:
	MOV	SP,#5FH		;ÉèÖÃ¶ÑÕ»
	MOV	P1,#0FFH
	MOV	P0,#0FFH
	MOV	P2,#0FFH	;³õÊ¼»¯£¬ËùÏÔÊ¾Æ÷£¬LEDÃð
	MOV	TMOD,#00000001B	;¶¨Ê±Æ÷T0¹¤×÷ÓÚÄ£Ê½1£¨16Î»¶¨Ê±/¼ÆÊýÄ£Ê½£©
	MOV	TH0,#HIGH(65536-2000)
	MOV	TL0,#LOW(65536-2000)
	SETB	TR0
	SETB	EA
	SETB	ET0
	MOV	Counter,#0	;¼ÆÊýÆ÷³õÊ¼»¯
	MOV	DISPBUFF,#0	;µÚÒ»Î»Ê¼ÖÕÏÔÊ¾0
	MOV	A,#0
LOOP:	
	MOV	DISPBUFF+1,A	;µÚ¶þÎ»ÂÖÁ÷ÏÔÊ¾0-9
	INC	A
	LCALL	DELAY
	CJNE	A,#10,LOOP
	MOV	A,#0
	AJMP	LOOP
;Ö÷³ÌÐòµ½´Ë½áÊø
DISP:
	PUSH	ACC		;ACCÈëÕ»
	PUSH	PSW		;PSWÈëÕ»
	MOV	TH0,#HIGH(65536-2000)
	MOV	TL0,#LOW(65536-2000)
	SETB	FIRST
	SETB	SECOND		;¹ØÏÔÊ¾
	MOV	A,#DISPBUFF	;ÏÔÊ¾»º³åÇøÊ×µØÖ·»
	ADD	A,Counter	
	MOV	R0,A
	MOV	A,@R0		;¸ù¾Ý¼ÆÊýÆ÷µÄÖµÈ¡ÏàÓ¦µÄÏÔÊ¾»º³åÇøµÄÖµ
	MOV	DPTR,#DISPTAB	;×ÖÐÎ±íÊ×µØÖ·
	MOVC	A,@A+DPTR	;È¡×ÖÐÎÂë
	MOV	P0,A		;½«×ÖÐÎÂëËÍP0Î»£¨¶Î¿Ú£©
	MOV	A,Counter	;È¡¼ÆÊýÆ÷µÄÖµ
	JZ	DISPFIRST	;Èç¹ûÊÇ0ÔòÏÔÊ¾µÚÒ»Î»
	CLR	SECOND		;·ñÔòÏÔÊ¾µÚ¶þÎ»
	AJMP	DISPSECOND
DISPFIRST:
	CLR	FIRST		;ÏÔÊ¾µÚÒ»Î»		
DISPSECOND:
	INC	Counter		;¼ÆÊýÆ÷¼Ó1
	MOV	A,Counter	
	DEC	A		;Èç¹û¼ÆÊýÆ÷¼Æµ½2Íû£¬ÔòÈÃËü»Ø0
	DEC	A		
	JZ	RSTCOUNT	
	AJMP	DISPNEXT
RSTCOUNT:
	MOV	Counter,#0	;¼ÆÊýÆ÷µÄÖµÖ»ÄÜÊÇ0»ò1
DISPNEXT:

	POP	PSW
	POP	ACC
	RETI
DELAY:			;ÑÓÊ±130ºÁÃë
	PUSH	PSW
	SETB	RS0
	MOV	R7,#255
D1:	MOV	R6,#255
D2:	NOP
	NOP
	NOP
	NOP
	DJNZ	R6,D2
	DJNZ	R7,D1
	POP	PSW
	RET
DISPTAB:DB 28H,7EH,0a4H,64H,72H,61H,21H,7CH,20H,60H	
	END
